// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package core

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *FlatLogRecord) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "timestamp":
			z.Timestamp, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "observedTimestamp":
			z.ObservedTimestamp, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "ObservedTimestamp")
				return
			}
		case "insertedAt":
			z.InsertedAt, err = dc.ReadTime()
			if err != nil {
				err = msgp.WrapError(err, "InsertedAt")
				return
			}
		case "traceId":
			z.TraceId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TraceId")
				return
			}
		case "spanId":
			z.SpanId, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SpanId")
				return
			}
		case "severityText":
			z.SeverityText, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SeverityText")
				return
			}
		case "severityNumber":
			z.SeverityNumber, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "SeverityNumber")
				return
			}
		case "serviceName":
			z.ServiceName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ServiceName")
				return
			}
		case "body":
			z.Body, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
		case "bodyType":
			z.BodyType, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "BodyType")
				return
			}
		case "scopeName":
			z.ScopeName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ScopeName")
				return
			}
		case "scopeVersion":
			z.ScopeVersion, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "ScopeVersion")
				return
			}
		case "logAttrKeys":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "LogAttrKeys")
				return
			}
			if cap(z.LogAttrKeys) >= int(zb0002) {
				z.LogAttrKeys = (z.LogAttrKeys)[:zb0002]
			} else {
				z.LogAttrKeys = make([]string, zb0002)
			}
			for za0001 := range z.LogAttrKeys {
				z.LogAttrKeys[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LogAttrKeys", za0001)
					return
				}
			}
		case "logAttrValues":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "LogAttrValues")
				return
			}
			if cap(z.LogAttrValues) >= int(zb0003) {
				z.LogAttrValues = (z.LogAttrValues)[:zb0003]
			} else {
				z.LogAttrValues = make([]string, zb0003)
			}
			for za0002 := range z.LogAttrValues {
				z.LogAttrValues[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "LogAttrValues", za0002)
					return
				}
			}
		case "resAttrkeys":
			var zb0004 uint32
			zb0004, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ResAttrKeys")
				return
			}
			if cap(z.ResAttrKeys) >= int(zb0004) {
				z.ResAttrKeys = (z.ResAttrKeys)[:zb0004]
			} else {
				z.ResAttrKeys = make([]string, zb0004)
			}
			for za0003 := range z.ResAttrKeys {
				z.ResAttrKeys[za0003], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ResAttrKeys", za0003)
					return
				}
			}
		case "resAttrValues":
			var zb0005 uint32
			zb0005, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "ResAttrValues")
				return
			}
			if cap(z.ResAttrValues) >= int(zb0005) {
				z.ResAttrValues = (z.ResAttrValues)[:zb0005]
			} else {
				z.ResAttrValues = make([]string, zb0005)
			}
			for za0004 := range z.ResAttrValues {
				z.ResAttrValues[za0004], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "ResAttrValues", za0004)
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *FlatLogRecord) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 16
	// write "timestamp"
	err = en.Append(0xde, 0x0, 0x10, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = en.WriteTime(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// write "observedTimestamp"
	err = en.Append(0xb1, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = en.WriteTime(z.ObservedTimestamp)
	if err != nil {
		err = msgp.WrapError(err, "ObservedTimestamp")
		return
	}
	// write "insertedAt"
	err = en.Append(0xaa, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74)
	if err != nil {
		return
	}
	err = en.WriteTime(z.InsertedAt)
	if err != nil {
		err = msgp.WrapError(err, "InsertedAt")
		return
	}
	// write "traceId"
	err = en.Append(0xa7, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.TraceId)
	if err != nil {
		err = msgp.WrapError(err, "TraceId")
		return
	}
	// write "spanId"
	err = en.Append(0xa6, 0x73, 0x70, 0x61, 0x6e, 0x49, 0x64)
	if err != nil {
		return
	}
	err = en.WriteString(z.SpanId)
	if err != nil {
		err = msgp.WrapError(err, "SpanId")
		return
	}
	// write "severityText"
	err = en.Append(0xac, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x54, 0x65, 0x78, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.SeverityText)
	if err != nil {
		err = msgp.WrapError(err, "SeverityText")
		return
	}
	// write "severityNumber"
	err = en.Append(0xae, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.SeverityNumber)
	if err != nil {
		err = msgp.WrapError(err, "SeverityNumber")
		return
	}
	// write "serviceName"
	err = en.Append(0xab, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.ServiceName)
	if err != nil {
		err = msgp.WrapError(err, "ServiceName")
		return
	}
	// write "body"
	err = en.Append(0xa4, 0x62, 0x6f, 0x64, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Body)
	if err != nil {
		err = msgp.WrapError(err, "Body")
		return
	}
	// write "bodyType"
	err = en.Append(0xa8, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.BodyType)
	if err != nil {
		err = msgp.WrapError(err, "BodyType")
		return
	}
	// write "scopeName"
	err = en.Append(0xa9, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.ScopeName)
	if err != nil {
		err = msgp.WrapError(err, "ScopeName")
		return
	}
	// write "scopeVersion"
	err = en.Append(0xac, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	if err != nil {
		return
	}
	err = en.WriteString(z.ScopeVersion)
	if err != nil {
		err = msgp.WrapError(err, "ScopeVersion")
		return
	}
	// write "logAttrKeys"
	err = en.Append(0xab, 0x6c, 0x6f, 0x67, 0x41, 0x74, 0x74, 0x72, 0x4b, 0x65, 0x79, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.LogAttrKeys)))
	if err != nil {
		err = msgp.WrapError(err, "LogAttrKeys")
		return
	}
	for za0001 := range z.LogAttrKeys {
		err = en.WriteString(z.LogAttrKeys[za0001])
		if err != nil {
			err = msgp.WrapError(err, "LogAttrKeys", za0001)
			return
		}
	}
	// write "logAttrValues"
	err = en.Append(0xad, 0x6c, 0x6f, 0x67, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.LogAttrValues)))
	if err != nil {
		err = msgp.WrapError(err, "LogAttrValues")
		return
	}
	for za0002 := range z.LogAttrValues {
		err = en.WriteString(z.LogAttrValues[za0002])
		if err != nil {
			err = msgp.WrapError(err, "LogAttrValues", za0002)
			return
		}
	}
	// write "resAttrkeys"
	err = en.Append(0xab, 0x72, 0x65, 0x73, 0x41, 0x74, 0x74, 0x72, 0x6b, 0x65, 0x79, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ResAttrKeys)))
	if err != nil {
		err = msgp.WrapError(err, "ResAttrKeys")
		return
	}
	for za0003 := range z.ResAttrKeys {
		err = en.WriteString(z.ResAttrKeys[za0003])
		if err != nil {
			err = msgp.WrapError(err, "ResAttrKeys", za0003)
			return
		}
	}
	// write "resAttrValues"
	err = en.Append(0xad, 0x72, 0x65, 0x73, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.ResAttrValues)))
	if err != nil {
		err = msgp.WrapError(err, "ResAttrValues")
		return
	}
	for za0004 := range z.ResAttrValues {
		err = en.WriteString(z.ResAttrValues[za0004])
		if err != nil {
			err = msgp.WrapError(err, "ResAttrValues", za0004)
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *FlatLogRecord) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 16
	// string "timestamp"
	o = append(o, 0xde, 0x0, 0x10, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o = msgp.AppendTime(o, z.Timestamp)
	// string "observedTimestamp"
	o = append(o, 0xb1, 0x6f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o = msgp.AppendTime(o, z.ObservedTimestamp)
	// string "insertedAt"
	o = append(o, 0xaa, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74)
	o = msgp.AppendTime(o, z.InsertedAt)
	// string "traceId"
	o = append(o, 0xa7, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64)
	o = msgp.AppendString(o, z.TraceId)
	// string "spanId"
	o = append(o, 0xa6, 0x73, 0x70, 0x61, 0x6e, 0x49, 0x64)
	o = msgp.AppendString(o, z.SpanId)
	// string "severityText"
	o = append(o, 0xac, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x54, 0x65, 0x78, 0x74)
	o = msgp.AppendString(o, z.SeverityText)
	// string "severityNumber"
	o = append(o, 0xae, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72)
	o = msgp.AppendUint8(o, z.SeverityNumber)
	// string "serviceName"
	o = append(o, 0xab, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.ServiceName)
	// string "body"
	o = append(o, 0xa4, 0x62, 0x6f, 0x64, 0x79)
	o = msgp.AppendString(o, z.Body)
	// string "bodyType"
	o = append(o, 0xa8, 0x62, 0x6f, 0x64, 0x79, 0x54, 0x79, 0x70, 0x65)
	o = msgp.AppendString(o, z.BodyType)
	// string "scopeName"
	o = append(o, 0xa9, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.ScopeName)
	// string "scopeVersion"
	o = append(o, 0xac, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
	o = msgp.AppendString(o, z.ScopeVersion)
	// string "logAttrKeys"
	o = append(o, 0xab, 0x6c, 0x6f, 0x67, 0x41, 0x74, 0x74, 0x72, 0x4b, 0x65, 0x79, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.LogAttrKeys)))
	for za0001 := range z.LogAttrKeys {
		o = msgp.AppendString(o, z.LogAttrKeys[za0001])
	}
	// string "logAttrValues"
	o = append(o, 0xad, 0x6c, 0x6f, 0x67, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.LogAttrValues)))
	for za0002 := range z.LogAttrValues {
		o = msgp.AppendString(o, z.LogAttrValues[za0002])
	}
	// string "resAttrkeys"
	o = append(o, 0xab, 0x72, 0x65, 0x73, 0x41, 0x74, 0x74, 0x72, 0x6b, 0x65, 0x79, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ResAttrKeys)))
	for za0003 := range z.ResAttrKeys {
		o = msgp.AppendString(o, z.ResAttrKeys[za0003])
	}
	// string "resAttrValues"
	o = append(o, 0xad, 0x72, 0x65, 0x73, 0x41, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.ResAttrValues)))
	for za0004 := range z.ResAttrValues {
		o = msgp.AppendString(o, z.ResAttrValues[za0004])
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *FlatLogRecord) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "timestamp":
			z.Timestamp, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "observedTimestamp":
			z.ObservedTimestamp, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ObservedTimestamp")
				return
			}
		case "insertedAt":
			z.InsertedAt, bts, err = msgp.ReadTimeBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "InsertedAt")
				return
			}
		case "traceId":
			z.TraceId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TraceId")
				return
			}
		case "spanId":
			z.SpanId, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SpanId")
				return
			}
		case "severityText":
			z.SeverityText, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SeverityText")
				return
			}
		case "severityNumber":
			z.SeverityNumber, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SeverityNumber")
				return
			}
		case "serviceName":
			z.ServiceName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ServiceName")
				return
			}
		case "body":
			z.Body, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Body")
				return
			}
		case "bodyType":
			z.BodyType, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BodyType")
				return
			}
		case "scopeName":
			z.ScopeName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ScopeName")
				return
			}
		case "scopeVersion":
			z.ScopeVersion, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ScopeVersion")
				return
			}
		case "logAttrKeys":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LogAttrKeys")
				return
			}
			if cap(z.LogAttrKeys) >= int(zb0002) {
				z.LogAttrKeys = (z.LogAttrKeys)[:zb0002]
			} else {
				z.LogAttrKeys = make([]string, zb0002)
			}
			for za0001 := range z.LogAttrKeys {
				z.LogAttrKeys[za0001], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LogAttrKeys", za0001)
					return
				}
			}
		case "logAttrValues":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LogAttrValues")
				return
			}
			if cap(z.LogAttrValues) >= int(zb0003) {
				z.LogAttrValues = (z.LogAttrValues)[:zb0003]
			} else {
				z.LogAttrValues = make([]string, zb0003)
			}
			for za0002 := range z.LogAttrValues {
				z.LogAttrValues[za0002], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "LogAttrValues", za0002)
					return
				}
			}
		case "resAttrkeys":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ResAttrKeys")
				return
			}
			if cap(z.ResAttrKeys) >= int(zb0004) {
				z.ResAttrKeys = (z.ResAttrKeys)[:zb0004]
			} else {
				z.ResAttrKeys = make([]string, zb0004)
			}
			for za0003 := range z.ResAttrKeys {
				z.ResAttrKeys[za0003], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ResAttrKeys", za0003)
					return
				}
			}
		case "resAttrValues":
			var zb0005 uint32
			zb0005, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ResAttrValues")
				return
			}
			if cap(z.ResAttrValues) >= int(zb0005) {
				z.ResAttrValues = (z.ResAttrValues)[:zb0005]
			} else {
				z.ResAttrValues = make([]string, zb0005)
			}
			for za0004 := range z.ResAttrValues {
				z.ResAttrValues[za0004], bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ResAttrValues", za0004)
					return
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *FlatLogRecord) Msgsize() (s int) {
	s = 3 + 10 + msgp.TimeSize + 18 + msgp.TimeSize + 11 + msgp.TimeSize + 8 + msgp.StringPrefixSize + len(z.TraceId) + 7 + msgp.StringPrefixSize + len(z.SpanId) + 13 + msgp.StringPrefixSize + len(z.SeverityText) + 15 + msgp.Uint8Size + 12 + msgp.StringPrefixSize + len(z.ServiceName) + 5 + msgp.StringPrefixSize + len(z.Body) + 9 + msgp.StringPrefixSize + len(z.BodyType) + 10 + msgp.StringPrefixSize + len(z.ScopeName) + 13 + msgp.StringPrefixSize + len(z.ScopeVersion) + 12 + msgp.ArrayHeaderSize
	for za0001 := range z.LogAttrKeys {
		s += msgp.StringPrefixSize + len(z.LogAttrKeys[za0001])
	}
	s += 14 + msgp.ArrayHeaderSize
	for za0002 := range z.LogAttrValues {
		s += msgp.StringPrefixSize + len(z.LogAttrValues[za0002])
	}
	s += 12 + msgp.ArrayHeaderSize
	for za0003 := range z.ResAttrKeys {
		s += msgp.StringPrefixSize + len(z.ResAttrKeys[za0003])
	}
	s += 14 + msgp.ArrayHeaderSize
	for za0004 := range z.ResAttrValues {
		s += msgp.StringPrefixSize + len(z.ResAttrValues[za0004])
	}
	return
}
