site_name: Logarithm
site_url: https://mydomain.org/mysite

nav:
  - Home: index.md
  - Configuration: 
    - Environment Variables: environment.md
  - Integration with OpenTelemetry: otel.md
  - Infrastructure: 
      - Clickhouse: clickhouse.md

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: indigo
    # Light Mode
    - scheme: default 
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg 
